googleapis/storage-testbench

docs/code-of-conduct.md
The Contributor Covenant requires a named person for conflict resolution.
Adding myself for now, for redundancy we should have additional volunteers.
=> Add myself as steward for the CoC

gcs/__init__.py, gcs/bucket.py, gcs/holder.py, tests/test_bucket.py, tests/test_holder.py
Add helpers for uploads and rewrites, they are not quite a "resource",
but are long-lived entities in the testbench. Also added some bits of
the Bucket resource because I needed them for the tests.
=> feat: helpers for uploads and rewrites

gcs/bucket.py, tests/test_bucket.py
See the discussion in #30 for details.
=> fix: buckets should always have a metageneration

testbench/__init__.py, testbench/database.py, tests/test_database.py
testbench.database will hold all the resources (Bucket, Object, etc.) so
the Flask and gRPC applications can find them and implement the various
RPCs associated with them.
=> feat: add initial resource database

testbench/database.py, tests/test_database.py
The database needs to hold uploads and rewrites so they can be used
across RPCs.
=> feat: support uploads and rewrites in the database

.github/sync-repo-settings.yaml
I am not sure why I added that.
=> chore: remove clang-format from sync-repo settings

emulator.py, testbench/common.py, testbench/error.py, testbench/generation.py, tests/test_emulator.py
The emulator wraps each RPC with a "retry test", a mechanism to inject
failures and exercise the retry path in the client libraries.  This
change adds the wrapper to the existing RPCs.
=> feat: add retry wrapper to emulator

emulator.py, tests/test_emulator_object_special.py
=> feat: add Object copy, compose and rewrite RPCs

tests/format_multipart_upload.py, tests/test_object.py
This function will be useful in other tests, it makes sense to move it
to its own file.
=> refactor: split format_multipart_upload

emulator.py, tests/test_emulator_retry.py
I found a couple of methods with the wrong names: one a clear typo, the
onther (`Permission` vs. `Permission*s*`) may be argued both ways. The
plural form matches the name in:
https://cloud.google.com/storage/docs/json_api/v1/buckets/testIamPermissions
So I went with that.
=> fix: method names in retry_test wrapper

emulator.py, tests/test_emulator_retry.py, tests/test_emulator_root.py
I am not sure where this is used (not in the C++ client library, and in
none of the existing tests), but it seems plausible that somehow it is
used in some other client library tests.
=> feat: add raise_error route

.github/workflows/build.yaml, tests/test_emulator_bucket.py, tests/test_emulator_object_metadata.py, tests/test_emulator_object_special.py, tests/test_emulator_object_upload.py
Python < 3.9 lacks dict union operators:
https://www.python.org/dev/peps/pep-0584
All the alternatives are ugly (otherwise they would not have added the
operator!). I decided to use the `{**a, **b}` formulation.
Fixes #64
=> chore: support Python < 3.9

gcs/object.py, testbench/common.py, tests/test_emulator_continue_after_fault_injection.py, tests/test_emulator_retry.py
We were calling `sys.exit(1)` to terminate a worker thread and
(hopefully) generate a `connection reset by peer` (or similar) error on
the client. This is not needed, as we explicitly close the socket a few
lines before. And it is harmful, because it terminates the worker
threads and eventually exhausts them.
With this change we just close the socket, and introduce a new test to
verify one can use the `return-broken-stream` or
`return-reset-connection` instructions multiple times.
Fixes #67.
/FYI: @BenWhitehead
=> fix: fault injection terminates worker threads

gcs/bucket.py, gcs/object.py, testbench/acl.py, tests/test_acl.py, tests/test_bucket.py, tests/test_common.py, tests/test_generation.py, tests/test_holder.py, tests/test_object.py
The storage/v2 protos do **not** include any requests to change metadata
in objects or buckets. This PR removes references to such requests, as
well as any code to support those RPCs.
=> cleanup: remove references to storage/v1 requests

emulator.py, gcs/bucket.py, gcs/object.py, testbench/common.py, tests/test_bucket.py, tests/test_common.py, tests/test_holder.py
The storage/v2 protos do not have an enum for projections. Remove it now
to make future PRs smaller.
=> cleanup: do not use gRPC projection enum

README.md
Address [previous review comments](https://github.com/googleapis/storage-testbench/pull/82#discussion_r697590730) and substitute "emulator" with "testbench" within README. 
We can do a scrub across the repo afterwards.
=> docs: align usage of testbench

emulator.py, gcs/bucket.py, gcs/object.py, testbench/common.py, testbench/database.py, tests/test_bucket.py, tests/test_common.py, tests/test_database.py, tests/test_object.py
The gRPC uses `projects/_/buckets/{bucket}` for bucket names, and uses
`{bucket}` for the `bucket_id` field. If we are going to keep the data
in proto form, I think it should use the proto values too.
=> cleanup: use storage/v2 bucket names

gcs/holder.py, tests/test_emulator_retry.py, tests/test_holder.py, tests/test_object.py
Rewrite the support functions (mostly in `holder.py`) for gRPC writes.
They now support resumable uploads, non-resumable uploads, and correctly
report a number of error conditions.
=> feat: support functions for storage/v2 gRPC writes

gcs/holder.py, tests/test_holder.py
When I decided to store the bucket names using the proto format I missed
one spot where we used the `.name` field in the context of REST
requests. Should be `.bucket_id`.
=> fix: correct bucket id in upload location

pyproject.toml, requirements.txt, setup.py
The intent is to use this with a github URL from `google-cloud-cpp`, or
from any other repository with similar needs. We do *NOT* anticipate
publishing this to PyPI.
This is my first time creating a Python package. It is likely that I am doing
something wrong.
=> feat: add support files for packaging

.github/workflows/build.yaml
We were running the unit (and integration) tests twice, once without
code coverage and once with coverage. That is duplicating work.
=> ci: speedup unit tests

gcs/bucket.py, gcs/holder.py, gcs/iam.py, gcs/object.py, gcs/project.py, testbench/acl.py, testbench/common.py, testbench/error.py, testbench/grpc_server.py, testbench/handle_gzip.py, testbench/rest_server.py, tests/test_bucket.py, tests/test_common.py, tests/test_error.py, tests/test_generation.py, tests/test_grpc_server.py, tests/test_handle_gzip.py, tests/test_holder.py, tests/test_object.py, tests/test_project.py, tests/test_testbench_bucket.py, tests/test_testbench_continue_after_fault_injection.py, tests/test_testbench_object_metadata.py, tests/test_testbench_object_special.py, tests/test_testbench_object_upload.py, tests/test_testbench_object_xml.py, tests/test_testbench_startup.py
The recommended order seems to be standard library modules, then
packages, then local modules.
=> cleanup: sort import directives

testbench/database.py, testbench/grpc_server.py, testbench/rest_server.py, tests/test_database.py
Using the original request context is a bad idea. First, because
we really are using the REST code path, and second because
we really do not want to send errors back to the application
if this fails.
=> fix: automatically created bucket and gRPC

testbench/common.py, testbench/database.py, tests/test_testbench_retry.py
The database object is a global, shared by many threads. While we could
get away without synchronization (because there is no I/O in it to cause
a thread switch), we shouldn't.
Also renamed all the database fields to ensure they are always accessed
via a method that has the right locking. This is where near 100% code
coverage comes handy.
=> fix: use locks when accessing the database

Dockerfile
Port forwarding seems to be critical when using Docker on MacOS
=> fix: docker port forwarding doens't work when gunicorn binds to localhost

testbench/rest_server.py
Fixes #116 for the Go conformance tests, which use the lock method and need an effective time to parse.
=> fix: add retention_policy.effective_time when locking a policy

testbench/common.py, tests/test_common.py
A bug was happening where fields wasn't working properly and it was
leaving nested empty dicts in the response. This should clear that up,
by changing nested_keys function so that it includes parent keys also.
=> fix: cleanup filter_response_rest and nested_keys

README.md, gcs/bucket.py, google/storage/v2/storage_pb2.py, patches/rpo-and-cdr.patch, tests/test_bucket.py
Add support for the Recovery Point Objective (RPO) and Custom Dual
Regions (CDR) attributes in a bucket. This unblocks development and
testing for the client libraries.
=> feat: support RPO and CDR fields in Bucket

setup.py
The pip package has been broken since #114, I just did not notice because my builds were pinned to v0.4.0.
=> fix: missing directory is setup.py

README.md, setup.py
This dependency is only needed for development, and then only rarely.
=> cleanup: grpcio-tools is not needed to install/run

gcs/object.py, testbench/rest_server.py, tests/test_object.py, tests/test_testbench_object_xml.py
The testbench was not generating some `x-goog-*` headers. I will need
these headers in the C++ client library.
=> feat: support additional x-goog-* headers

gcs/upload.py, testbench/database.py, testbench/generation.py, testbench/grpc_server.py, testbench/rest_server.py, tests/test_database.py, tests/test_generation.py, tests/test_grpc_server.py
This simplifies precondition handling for `Database.*_object()`. The
caller needs to provide the generation (which can be `None` or `0`) and
the preconditions as a list of predicates on the blob and the live
generation.
In general, this makes the code more readable, albeit more verbose,
because the caller knows how the preconditions are represented in the
different transports (e.g. headers in XML, query parameters in JSON,
proto fields in gRPC), and in some cases the preconditions have
different names (e.g. `ifSource*` for `Objects: copy` or `Objects:
rewrite`).
Part of the work for #217
=> cleanup: simplify object precondition handling

testbench/database.py, testbench/rest_server.py, tests/test_testbench_object_metadata.py
I accidentally broke object deletes when a generation number is
provided.  We had no tests for this (now we do). Turns out in REST the
generation was a string, and the code was expecting an `int`. I added a
test (that reproduced the problem), and also some type annotations
(which seem to help very little).
=> fix: object deletes with a generation

README.md
=> docs: clarify that gRPC must run on different port

testbench/grpc_server.py, tests/test_grpc_server.py
I thought my previous tests had reproduced and fixed the problem, but
evidently this is not the case.  It all seems to be working correctly
now, tested using the C++ client library.  I also filed a bug against
the protobuf project, and another bug to cleanup this code when the
protobuf bug is fixed.
See #270 for more details.
=> fix(grpc): more problems with UpdateObject()/UpdateBucket()

setup.py
This is a double bump because we had two releases since the last update.
=> chore: bump version number after v0.14.0

README.md, testbench/common.py, testbench/database.py, tests/test_testbench_retry.py
Fixes #173
This introduces support for `return-broken-stream-after-YK` of downloaded data in the Retry Test API. 
To better test complex download scenarios in the retry conformance tests, we've discussed to test larger files and add support for "after-YK" instead of "after-YB"
=> feat: add support for return-broken-stream-after-YK

gcs/bucket.py, tests/test_bucket_grpc.py, tests/test_grpc_server.py
This was breaking some of my integration tests for the C++ client library, but only for buckets created with gRPC. Sigh.
=> fix(grpc): correct prefix for project resources

testbench/grpc_server.py, tests/test_grpc_server.py
Fix gRPC implementation of TestIamPermissions to echo the request `permissions` back in the response unfiltered. This is the behavior of the HTTP implementation, and they should be consistent. Since the HTTP implementation preceded the gRPC one, and the gRPC behavior was more restrictive, in order to retain backwards compatibility for existing HTTP tests, gRPC must be adjusted to match HTTP rather than the other way around.
=> fix(grpc): align grpc TestIamPermissions with http

testbench/database.py, testbench/grpc_server.py
I thought only grpc-created buckets had the bucket name prefixed as a resource, but both do. This meant that http List Bucket calls with Prefix never worked unless the full project resource name was also part of the prefix.
Fixes the fix for #314.
=> fix: prepend bucket name prefix for both transports

tests/test_echo.py
I am planning to remove the dependency on the `httpbin` module. This
adds some tests to verify the replacement largely works as the current
implementation.
Part of the work for #306
=> test: add httpbin tests

tests/test_testbench_startup.py
Future versions of Werkzeug use a slightly different format for the
startup message.  Relax the matcher so it works with both versions.
Part of the work for #321
=> test: relax startup matcher

testbench/grpc_server.py
Similar to `acl`, replace entire list of `default_object_acl` in `UpdateBucket` as there is no separate API for patch vs. update in gRPC
=> fix: replace default_object_acl in grpc update bucket op

setup.py, testbench/rest_server.py, testbench/servers/echo.py
Implement a new flask application to echo back http requests. This is
used in the C++ client library, where we implement our own HTTP helpers
and we need some kind of integration tests.  The existing module
(httpbin) seems to be unsupported, and it growing stale.
Fixes #321
=> feat: replace httpbin

.github/workflows/build.yaml
Python 3.6 went EOL about 4 months ago.
=> ci: stop testing with Python 3.6

testbench/common.py, tests/test_testbench_retry.py
Motivated by googleapis/google-cloud-cpp#8286
=> fix: preserve headers through retry test decorator

testbench/proto2rest.py, testbench/rest_server.py, tests/test_proto2rest.py, tests/test_testbench_bucket.py
Add attributes not present in the protos.
Part of the work for #338
=> feat: improve `BucketAcl: *` responses

gcs/object.py, testbench/proto2rest.py, tests/test_proto2rest.py
Move the functions to enrich the REST representation of objects to a
separate file.  I am plannning to further refactor this code to improve the
values returned by `ObjectAccessControl: *` RPCs.
Part of the work for #338
=> refactor: split object proto2rest functions

testbench/common.py, testbench/proto2rest.py, testbench/rest_server.py, tests/test_proto2rest.py, tests/test_testbench_object_metadata.py
Always use the helper functions in `proto2rest` when converting
`storage_pb2.ObjectAccessControl` to their REST representation.  Needed
some light refactoring in the `proto2rest` module to make this work.
Part of the work for #338
=> feat: enrich `ObjectAccessControl` REST responses

testbench/proto2rest.py, testbench/rest_server.py, tests/test_proto2rest.py, tests/test_testbench_bucket.py
Just like for bucket and object access controls, we need to enrich the
responses for `DefaultObjectAccessControl: *`.  I also made the testing
more consistent across all three resources.
Fixes #338
=> feat: improve `DefaultObjectAccessControl: *` responses

gcs/object.py, testbench/grpc_server.py, tests/test_grpc_server.py
Fixes #351
PredefinedACL replaces the existing object ACL in `gRPC.UpdateObject`, `object.update` and `object.patch` operations
=> fix: predefinedACL replaces existing ACL in object patch/update

gcs/bucket.py
Convert camelCase (used with gRPC) to snakecase so required fields are captured in Notification operations
i.e. `PayloadFormat` to `payload_format`
=> fix: handle camel case in notifications ops

testbench/grpc_server.py
This line was causing failures previously when running tests
in Go, but it works when the check uses collections.Iterable
instead.
Fixes googleapis/google-cloud-go#6156
=> fix: gRPC logging check for iterable

testbench/grpc_server.py
Handle empty strings/zero values for predefinedACL
=> fix: handle predefinedACL empty strings

testbench/grpc_server.py
Use `0.0.0.0` when starting gRPC Server to unblock docker image usage.
=> fix: use 0.0.0.0 with gRPC

testbench/common.py, testbench/rest_server.py, testbench/servers/iam_rest_server.py, testbench/servers/projects_rest_server.py, tests/test_common.py
Fixes #379 
Adds gzip decompression support using the [`before_request` decorator](https://flask.palletsprojects.com/en/2.1.x/api/#flask.Flask.before_request)
- **adds** gzip decompression when `Content-Encoding: "gzip"` is present in request headers
- **no** decompression when object's metadata includes `contentEncoding: "gzip"` in upload requests so that we can store data compressed when applicable and preserve decompressive transcoding improvements made in #322
=> fix: support gzip decompression on metadata requests

gcs/object.py, testbench/error.py, tests/test_object.py
This adds validation to range download request headers
- testbench returns `206 Partial Content` for valid range download requests
- testbench returns `416 Requested Range Not Satisfiable` for invalid range headers
Fixes #396 and some of #331
=> feat: support status codes 206 and 416 for range downloads

testbench/grpc_server.py, testbench/rest_server.py, tests/test_grpc_server.py
gRPC server can now optionally echo request metadata for all RPC methods. Echoed headers are prefixed with 'x-req-'. The feature is controlled via an 'echo-metadata' query parameter to '/start_grpc'.
=> feat: support gRPC metadata echo

gcs/upload.py, testbench/rest_server.py, tests/test_testbench_object_upload.py, tests/test_upload.py
Fixes #402
This adds support for `X-GUploader-No-308: yes`  - if included in resumable upload request headers, instead of returning 308: resume incomplete, [return 200 to satisfy the client and add a X-HTTP-Status-Code-Override: 308 response header](https://github.com/googleapis/storage-testbench/issues/go/scotty-faq#my-client-received-an-http-308-response-with-no-location-header)
=> feat: support request header X-Guploader-No-308

testbench/acl.py, testbench/proto2rest.py, tests/test_acl.py, tests/test_proto2rest.py
Some entities have two spellings.  gRPC will return both, allowing client libraries to implement *AccessControl operations using OCC loops.
=> feat: use `entity_alt` in `*AccessControl`

gcs/object.py, tests/test_object.py
Fixes https://github.com/googleapis/storage-testbench/issues/445
The end byte for the range header in the response is incorrect.  
Before:
```
$ curl -v   'http://localhost:9000/storage/v1/b/test_bucket/o/hello.txt?alt=media' --header 'Range: bytes=0-2'   2>&1 | grep Content-Rang
e
< Content-Range: bytes 0-1/10
```
After:
```
$ curl -v   'http://localhost:9000/storage/v1/b/test_bucket/o/hello.txt?alt=media' --header 'Range: bytes=0-2'   2>&1 | grep Content-Range
< Content-Range: bytes 0-2/10
```
=> fix: Use the correct range in response header

.github/workflows/build.yaml, Dockerfile, README.md, setup.py, testbench/common.py, testbench_run.py, testbench_waitress.py, tests/test_testbench_continue_after_fault_injection.py, tests/test_testbench_object_upload.py, tests/test_testbench_run.py, tests/test_testbench_startup.py, tests/test_testbench_waitress.py
As gunicorn is not supported on windows , these changes are to dynamically switch between waitress and gunicorn, so that waitress can be used as a server whenever the testbench is on windows , otherwise gunicorn.
Also added new job in build.yaml to test storage test bench on windows.
=> feat: Support both `waitress` and `gunicorn` servers

.codecov.yml
The ignore list was plain wrong. With this change we ignore the generated files in `google/iam` and `google/storage`.
=> ci: fix ignore list for code coverage

gcs/bucket.py, tests/test_bucket_grpc.py
In gRPC we need to support project names in both the `parent` field and
the `bucket.project` fields.  Add some code to validate the field in
either case.
=> feat(gRPC): validate both project fields

testbench/grpc_server.py, tests/test_grpc_server.py
Buckets have labels that can be updated or removed individually. The analog for the object metadata are (confunsingly) called "metadata".
=> feat(gRPC): support metadata and label updates

testbench/grpc_server.py, tests/test_grpc_server.py
When gRPC ReadObject has a byte range request, set the ContentRange field.
=> Fix: ReadObject with byte ranges sets ContentRange

gcs/upload.py, tests/test_grpc_server.py
For the gRPC WriteObject path, the preconditions are put in WriteObjecSpec rather
than directly in the request, like other objects.
=> Fix: precondition creation in WriteObject

testbench/grpc_server.py, tests/test_grpc_server.py
When a GCS request is made, read_offset is compared with the object size, and if it's too large, an error is returned.
=> fix(gRPC): validate ReadObject.read_offset

gcs/object.py
Previously, generation is generated from a timestamp; multiple concurrent requests can result in the same value when it should be unique.
This is an attempt to improve flaky concurrent tests so I can use storage-testbench in the http://github.com/google/tensorstore repository.
=> feat: ensure generation is distinct

testbench/database.py
Generation as passed in here is a string, leading to weird failures in some cases.
=> fix: use correct types for generation

testbench/common.py, testbench/database.py, testbench/error.py, testbench/grpc_server.py, testbench/rest_server.py, tests/test_common.py, tests/test_database.py, tests/test_error.py, tests/test_testbench_retry.py
-  Initial scaffolding for new retry test handler in the gRPC server 
- enable method `GetBucket`
- error-codes-matches (e.g. return-503) 
- retry_connection_matches (e.g. return-reset-connection)
- Add new field `"transport": "JSON"` to the Retry Test Resource
- trigger retry test cases for specified transport(s), returns 501 Unimplemented for operations not yet supported 
- validate and distinguish retry test instructions for specified transport
- Add error code mapping between HTTP and gRPC
- Appropriate changes to README will be added when the support is completed
=> feat: initial scaffolding to add Retry Test API in gRPC

README.md, gcs/upload.py, testbench/common.py, testbench/database.py, testbench/grpc_server.py, tests/test_testbench_retry.py
Add Retry Test API support for return-X-after-YK in gRPC WriteObject
=> feat: support retry test return-X-after-YK for uploads in grpc

.github/workflows/build.yaml, setup.py
`Werkzeug` is a direct dependency, we should pin it too. I also noticed the Python version needed fixing. And it would be nice to see what is installed for troubleshooting purposes.
Motivated by #547
=> fix: pin `Werkzeug` version

setup.py
=> feat: support pipx

.github/workflows/build.yaml
Only upload code coverage results for Python 3.11 on Linux. Uploading all the results seems to flake (maybe too may parallel uploads?).
=> ci: deflake code coverage uploads

testbench/database.py, testbench/grpc_server.py, testbench/rest_server.py
Tensorstore has a test which does concurrent reads/writes to storage testbench.
(https://github.com/google/tensorstore/blob/41812f367837989d91c7e1ae8548ecfa166e70be/tensorstore/kvstore/gcs_grpc/gcs_grpc_testbench_test.cc#L169)
The test spawns N threads. Each thread uses conditional operations to atomically update a region of the object.
This test currently is flaky due to missing object locking in storage-testbench.
Before this change, the database returned an object which was modified outside of the lock.
After this change, the modifications to the database object happen while a lock is held.
=> fix: races in Object metadata updates

gcs/upload.py, testbench/grpc_server.py, tests/test_upload.py
- Return object resource and finalize a resumable session for a `WriteObjectRequest` w/ `finish_write: true` w/o checksummed_data
- Apply grpc retry wrapper to `StartResumableWrite`
- Updated tests
Fixes #574
=> fix: handle WriteObject final message with empty data

gcs/upload.py, testbench/grpc_server.py, tests/test_grpc_server.py, tests/test_upload.py
=> feat(gRPC): implement BidiWriteObject

gcs/bucket.py, testbench/proto2rest.py, tests/test_bucket.py, tests/test_bucket_grpc.py
Part of the work for https://github.com/googleapis/google-cloud-cpp/issues/13575
=> feat: support bucket soft-delete policies

tests/test_testbench_object_gzip.py
`gzip.compress()` includes a timestamp in the output, which makes it non-deterministic:
https://docs.python.org/3/library/gzip.html#gzip.compress
We could fix the tests by setting `mtime` or by comparing the decompressed data.
I chose to decompress the data and compare the decompressed output, because that is what we care about.
=> test: deflake compression tests

gcs/upload.py, tests/test_upload.py
Context: mutation test caught missing test case in internal cl/609739391
Not sure why productive coverage check is angry as there is test coverage through
https://github.com/googleapis/storage-testbench/blob/a60a7145a67098e7c6cd4142391e240b3d462ecc/tests/test_grpc_server.py#L2113-L2151
=> test: add mutation test case

.github/CODEOWNERS
Drop @googleapis/cloud-cxx-owners (who no longer have Write privileges) as CODEOWNERS.
=> chore: drop cloud-cxx-team as CODEOWNERS

gcs/upload.py, testbench/grpc_server.py, tests/test_testbench_retry.py
This adds retry test api support in gRPC BidiWriteObject
=> feat: support retry test api in BidiWriteObject

gcs/object.py
Previously, if the requested byte range was truncated, an invalid content-range header was sent.
=> fix: send correct content-range header if requested byte range was truncated

testbench/database.py, testbench/grpc_server.py, tests/test_database.py
Allow more methods for Retry Test support in gRPC
- equip gRPC endpoints with @retry_test decorator
- update `__validate_grpc_method_implemented_retry` guard
- 501 Unimplemented exceptions are only raised for ACL and notifications test cases that are not applicable in gRPC
=> feat: enable more methods for retry test support in gRPC

.github/workflows/build.yaml
It seems that codecov.io now requires tokens for all uploads:
https://github.com/codecov/codecov-action?tab=readme-ov-file#v4-release
> **Breaking Changes** Tokenless uploading is unsupported
=> ci: provide codecov with its token

testbench/common.py
This is needed to test behavior with DEADLINE_EXCEEDED errors for gRPC. GCS is still returning these errors in some cases for internal timeouts so we need to be able to test this.
Fixes #<issue_number_goes_here>
=> fix: map 504 errors to DEADLINE_EXCEEDED

cloudbuild.yaml
=> fix: Update cloudbuild.yaml to use $SHORT_SHA to infra tag images

testbench/database.py, testbench/error.py, testbench/grpc_server.py, testbench/rest_server.py, tests/test_database.py, tests/test_error.py, tests/test_grpc_server.py, tests/test_testbench_object_metadata.py, tests/test_testbench_object_special.py
=> feat: add object restore functionality

cloudbuild.yaml
This also fixes an issue with the infrastructure-public-image tagging.
=> Fix: Update cloudbuild.yaml to combine the build and tag steps

gcs/object.py, testbench/grpc_server.py, testbench/rest_server.py, tests/test_grpc_server.py, tests/test_testbench_object_special.py
Fixes #<issue_number_goes_here>
=> feat: add MoveObject to json and grpc

README.md, gcs/upload.py, testbench/common.py, testbench/grpc_server.py, tests/test_testbench_retry.py
Fixes Redirection in case of BidiReadObject. 
This adds instructions for returning a redirect error which includes the read_handle in details.
Other redirections( without read_handle ) are not possible in case of BidiRead.
=> feat(read): add redirect semantics for BidiReadObject

gcs/upload.py, tests/test_grpc_server.py
Updates `blob.metadata.checksums.crc32c` for an appendable blob
Towards #720 and related to #721
=> feat: update appendable blob metadata crc32c field

gcs/upload.py, testbench/grpc_server.py
The server generally won't know if a redirect is required until it sees the first message. Since this is the common case, do that in tests with redirect instructions.
=> fix: Get a message before redirecting.

testbench/grpc_server.py
Formatting content fields of up to 2MiB takes a long time, and we don't really care about them anyway. Show much less.
=> fix: Trim content fields longer than 10 bytes.
