googleapis/storage-testbench

.gitignore
requirements.txt
testbench/error.py
tests/test_error.py

This just copies some minimal amount of code from
https://github.com/google-cloud-cpp to bootstrap the project. I want to
add some CI builds and maybe code coverage before adding any other code.
Also, I am sure folks will tell me how the code is not organized correctly, the name are wrong, etc.

feat: minimal code to bootstrap project

---

testbench/__init__.py
testbench/acl.py
testbench/common.py
tests/test_acl.py

Moving more helper functions from the `google-cloud-cpp` repository. The test file is new, though the tests did exist already.

feat: helpers for ACL manipulation

---

gcs/bucket.py
tests/test_bucket.py

feat: implement Bucket resource

---

gcs/__init__.py
gcs/object.py
tests/test_object.py

feat: start on Object resource

---

gcs/object.py
tests/test_object.py

feat: complete Object resource

---

testbench/database.py
tests/test_database.py

feat: add support for retry instructions in database

---

emulator.py
gcs/__init__.py
tests/test_emulator.py

feat: initial version of flask application

---

emulator.py
tests/test_emulator_object_xml.py

feat: add XML RPCs to emulator

---

emulator.py
tests/test_emulator.py

feat: add Bucket ACL RPCs to emulator

---

emulator.py
tests/test_emulator_object_metadata.py

feat: emulator add object CRUD operations

---

emulator.py
tests/test_emulator.py

feat: emulator add RPCs for default object ACL

---

emulator.py
tests/test_emulator_object_metadata.py

feat: add Object ACL RPCs to emulator

---

emulator.py
gcs/bucket.py
tests/test_bucket.py
tests/test_emulator.py

feat: add RPCs for Bucket notifications

---

emulator.py
tests/test_emulator.py

Part of the work for #24. This completes the bucket RPCs.  :shipit:

feat: add bucket IAM and retention policy RPCs

---

emulator.py
tests/test_emulator_object_upload.py

Part of the work for #24. This completes the RPCs for Object :rocket:

feat: add object upload and download RPCs

---

testbench/common.py
testbench/database.py
tests/test_common.py
tests/test_database.py
tests/test_emulator_retry.py

Part of the work for #24. Also fixes #54

feat: complete fault injection features

---

emulator.py
tests/test_emulator_startup.py

feat: add entry points for gunicorn and plain runs

---

README.md
google/storage/v2/storage_pb2.py

My `googleapis` clone was slightly out of date. Updated the README file
too since the previous version still referenced the testbench location
in `google-cloud-cpp`.

chore: update storage/v2 protos

---

gcs/bucket.py
gcs/object.py
testbench/common.py
tests/test_bucket.py
tests/test_common.py

fix: correctly implement REST patch operations

---

testbench/common.py
testbench/csek.py
tests/test_common.py

cleanup: use v2/ protos to initialize FakeRequest

---

gcs/holder.py
testbench/__init__.py
testbench/database.py
testbench/generation.py
testbench/grpc_server.py
tests/test_grpc_server.py
tests/test_holder.py

feat: implement ReadObject method for gRPC

---

testbench/database.py
testbench/grpc_server.py
tests/test_grpc_server.py

Part of the changes for #58, the only thing missing is a REST API to start the gRPC server.

feat: complete gRPC server implementation

---

testbench/rest_server.py
tests/test_testbench_startup.py

feat: add route to startup the gRPC server

---

.dockerignore
.github/workflows/docker.yaml
Dockerfile

The latest tag build failed. This should get it working again.

fix: restore docker build and add to CI

---

testbench/rest_server.py

fix: fields in objects.rewrite response should be strings

---

.github/CODEOWNERS

Fixes #<issue_number_goes_here>

chore: Update CODEOWNERS for @googleapis/cloud-storage-dpe

---

renovate.json

I think updating the Dockerfile once a week is more than enough.

chore: reduce frequency of Docker renovates

---

gcs/bucket.py
testbench/grpc_server.py
tests/test_bucket_grpc.py
tests/test_grpc_server.py

feat: implement CreateBucket on gRPC server

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement GetObject()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement GetBucket()

---

testbench/database.py
testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement ListObjects()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement DeleteObject()

---

gcs/__init__.py
gcs/upload.py
testbench/common.py
testbench/grpc_server.py
testbench/rest_server.py
tests/test_database.py
tests/test_object.py
tests/test_upload.py

refactor: rename DataHolder to Upload

---

testbench/generation.py
testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement UpdateObject()

---

gcs/bucket.py
testbench/grpc_server.py
tests/test_grpc_server.py

Some light refactoring and fixes in the Bucket class to propertly
initialize some fields.
Fixes #185

feat(grpc): implement UpdateBucket()

---

gcs/rewrite.py
tests/test_rewrite.py
tests/test_testbench_object_special.py

We need to support gRPC-created Rewrite objects.
Part of the work for #192

feat: support gRPC for Rewrite objects

---

testbench/common.py
tests/test_common.py

This is the first step to refactor precondition handling and simplify
how the testbench database is implemented.
Part of the work for #217

feat: helper functions for preconditions

---

testbench/common.py
tests/test_common.py

feat: helper functions for Bucket preconditions

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement ComposeObject()

---

testbench/common.py
tests/test_common.py

feat(grpc): preconditions for RewriteObject

---

testbench/csek.py
tests/test_common.py
tests/test_csek.py

feat(grpc): improve CSEK support

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement GetIamPolicy()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement DeleteBucket()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement RewriteObject()

---

gcs/bucket.py
testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement ListBuckets()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement TestIamPermissions()

---

gcs/bucket.py
testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement SetIamPolicy()

---

testbench/database.py
testbench/servers/projects_rest_server.py
tests/test_project.py

refactor: store projects in Database class

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement LockBucketRetentionPolicy()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement GetServiceAccount

---

.github/workflows/build.yaml

ci: expand test matrix

---

gcs/bucket.py
testbench/grpc_server.py
testbench/rest_server.py
tests/test_bucket.py
tests/test_grpc_server.py

feat(grpc): implement CreateNotification()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement CreateHmacKey()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement GetNotification()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement GetHmacKey()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement ListNotifications()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement ListHmacKeys()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement DeleteNotification()

---

gcs/project.py
tests/test_project.py

fix: error reporting on HmacKey updates

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement UpdateHmacKey()

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): valid topic name format

---

testbench/grpc_server.py
tests/test_grpc_server.py

feat(grpc): implement DeleteHmacKey()

---

README.md
google/storage/v2/storage_pb2.py

This version includes all the metadata operations, some fixes for
`CreateBucket()`, and it lives in the `main` branch of
`googleapis/googleapis`.

chore: update protos to version circa 2022-01-06

---

gcs/bucket.py
tests/test_grpc_server.py

feat(grpc): implement bucket pre-defined ACLs

---

README.md

docs: update README to include gRPC server startup

---

gcs/rewrite.py
google/storage/v2/storage_pb2.py
testbench/grpc_server.py
tests/test_grpc_server.py
tests/test_object.py
tests/test_rewrite.py

With the changes to the protos I had to change how the `RewriteObject()`
RPC works. The new protos used different fields to represent the
destination bucket and object.
Fixes #227, though not exactly as anticipated. Fixes #180 as #227 was the last item.

chore(deps): update protos circa 2022-01-27

---

testbench/grpc_server.py
tests/test_grpc_server.py

The implementation of both `UpdateObject()` and `UpdateBucket()` were not quite right when the metadata/labels replaced existing metadata or labels.

fix(grpc): support for UpdateObject/UpdateBucket

---

.github/workflows/style.yaml
gcs/object.py
setup.py

See https://github.com/postmanlabs/httpbin/issues/673 
I had to update the version of the Python formatting tool (`black`)  at the same time.

chore: pin indirect dependency (Werkzeug)

---

testbench/database.py
testbench/grpc_server.py
testbench/rest_server.py
tests/test_database.py
tests/test_grpc_server.py

fix: add prefix support to list_buckets

---

testbench/error.py
tests/test_testbench_retry.py

fix: format for `RestException` errors

---

setup.py

chore: bump version post v0.26.0

---

testbench/error.py

Received a request through chat to update the URL.

chore: update csek url in csek 400 error

---

testbench/rest_server.py
tests/test_testbench_object_upload.py

feat: support POST calls for uploading chunks in resumable uploads

---

tests/test_testbench_object_upload.py
tests/test_testbench_retry.py

At least with my version of Python (3.10.7) these tests did not pass.

test: fix operator priority

---

.github/workflows/style.yaml
gcs/bucket.py
gcs/object.py
gcs/upload.py
testbench/__init__.py
testbench/__main__.py
testbench/acl.py
testbench/common.py
testbench/grpc_server.py
testbench/proto2rest.py
testbench/rest_server.py
testbench/servers/echo.py
testbench/servers/projects_rest_server.py
testbench_run.py
testbench_waitress.py
tests/test_bucket_grpc.py
tests/test_common.py
tests/test_csek.py
tests/test_echo.py
tests/test_grpc_server.py
tests/test_object.py
tests/test_proto2rest.py
tests/test_testbench_continue_after_fault_injection.py
tests/test_testbench_object_gzip.py
tests/test_testbench_object_upload.py
tests/test_testbench_retry.py
tests/test_testbench_run.py
tests/test_testbench_startup.py
tests/test_upload.py

I think this makes it easier to maintain the code.  I would rather spend time thinking of more useful things.

cleanup: automatically sort imports

---

tests/test_csek.py

test: no `bytes` in HTTP headers

---

setup.py

We failed to update this in multiple releases, tsck tsck.

chore: update version

---

renovate.json

Update docker image only once a week.

chore: reduce renovate noise

---

.github/workflows/build.yaml

Still fails from time to time, time to put a retry loop around the upload.

ci: retry codecov upload

---

testbench/grpc_server.py
tests/test_grpc_server.py

Fixes #<issue_number_goes_here>

fix: plumb soft_deleted option for grpc GetObject

---

gcs/upload.py
tests/test_grpc_server.py

feat: update appendable blob size and media in unfinalized writes
